# Generated by Django 5.1.5 on 2025-02-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='text',
        ),
    ]
