# Generated by Django 5.1.5 on 2025-02-03 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0004_remove_blog_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
